services:
  - type: web
    name: recipebook
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: EDAMAM_APP_ID
        value: $EDAMAM_APP_ID
      - key: EDAMAM_API_KEY
        value: $EDAMAM_API_KEY
      - key: NODE_ENV
        value: production
    branch: main
    autoDeploy: true
