services:
  - type: web
    name: recipebook-backend
    env: node
    rootDir: server/api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: EDAMAM_APP_ID
        value: $EDAMAM_APP_ID
      - key: EDAMAM_API_KEY
        value: $EDAMAM_API_KEY
      - key: VITE_API_KEY
        value: $VITE_API_KEY
      - key: PORT
        value: 8080

  - type: web
    name: recipebook-frontend
    env: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://recipebook-backend-g6d9.onrender.com
