services:
  - type: web
    name: recipebook
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: EDAMAM_APP_ID
        value: $EDAMAM_APP_ID
      - key: EDAMAM_API_KEY
        value: $EDAMAM_API_KEY
      - key: NODE_ENV
        value: production
    buildImage: node:20
    healthCheck:
      path: /
      interval: 30s
      timeout: 5s
      unhealthyThreshold: 3
      healthyThreshold: 2
    instanceCount: 1
    instanceSize: free
    port: 8080
    diskSizeGb: 1
    env: node
    minReplicas: 1
    maxReplicas: 3
    autoDeploy: true
    gitRepo: https://github.com/bibimbop123/recipebook.git
    branch: main
    rootDirectory: .
databases:
  - name: recipebook-db
    plan: free
