services:
  - type: web
    name: recipebook
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EDAMAM_APP_ID
        value: your-edamam-app-id
      - key: EDAMAM_API_KEY
        value: your-edamam-api-key
      - key: VITE_API_URL
        value: https://recipebook-9dki.onrender.com
    branch: main
    autoDeploy: true
