services:
  - type: web
    name: recipebook-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: $RECIPEBOOK_API_URL
    httpHeaders:
      - name: Access-Control-Allow-Origin
        value: "*"
      - name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"
    ports:
      - port: 5173

  - type: web
    name: recipebook-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/api/server.js
    envVars:
      - key: REACT_APP_ID
        value: $REACT_APP_ID
      - key: REACT_APP_KEY
        value: $REACT_APP_KEY
    httpHeaders:
      - name: Access-Control-Allow-Origin
        value: "*"
      - name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization"
    ports:
      - port: 8080
databases:
  - name: recipebook-db
    plan: free
