services:
  - type: web
    name: recipebook-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: serve -s dist -l 4173
    envVars:
      - key: VITE_API_URL
        value: $RECIPEBOOK_API_URL


  - type: web
    name: recipebook-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server/api/server.js
    envVars:
      - key: REACT_APP_ID
        value: $REACT_APP_ID
      - key: REACT_APP_KEY
        value: $REACT_APP_KEY
databases:
  - name: recipebook-db
    plan: free
