services:
  - type: web
    name: recipebook-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    rootDir: client
    envVars:
      - key: VITE_API_URL
        value: https://recipebook-backend-xxxx.onrender.com # Replace after backend deploy

  - type: web
    name: recipebook-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: EDAMAM_APP_ID
        value: your-edamam-app-id
      - key: EDAMAM_API_KEY
        value: your-edamam-api-key
